/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 gameboy.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { useThree } from '@react-three/fiber';


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/3dmodel/gameboy.glb')

  let camera = useThree((state) => state.camera);

  useLayoutEffect(() => {
    let tl = gsap.timeline({
      scrollTrigger: {
        trigger: "#gameboy-model",
        start: "top top",
        end: "bottom+=1200 bottom",
        scrub: true,
      }
    });
      
    tl.fromTo(camera.position, { x: -200, y: 0, z: 300 }, { x: 0, y: 0, z: 250 })
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Box001_default_0.geometry} material={materials['default']} />
        <mesh geometry={nodes.Box001_default_0001.geometry} material={materials.default_0} />
      </group>
      <mesh geometry={nodes['Plane001_Material_#129_0'].geometry} material={materials.Material_129} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3dmodel/gameboy.glb')
